8
LiveNathan/javascript-labs pull request #2
Opened 2023-08-06 20:21 UTC by LiveNathan

Several of the APIs were either dead or changed, so I made some modifications.

2023-08-16 08:02 UTC, iansedano requested changes
Hi Nathan, great work!

I've left just a couple comments for now. They are quite high level suggestions that will affect much of the code, so I didn't want to get too nitty gritty. That said, there isn't much nitty gritty to pick on, anyway -- the code is well written!

The only thing that seems to not work well for me is the position of the sun and moon when rendered on the page.

In terms of the high level organization. I'd expect for most of the functions to be broken up so that each of their responsabilities are well defined. Especially when it comes to `fetch`. Generally the pattern that you use is:

- First write functions to request the data where you can handle all the errors that are typical to fetching.
- Then write functions to process/tidy your data.
- Then write functions to render your data.

As a final example. The sun position: you'll already have a function that just fetches world time data. Then have a function or functions that process the world time data and returnsa number that represents the position of the sun/moon. Then a function that takes this number and renders it on the page as the sun/moon.

Currently, the data processing is spread over two functions. First you have some logic to calculate the multiplier, that could be in it's own function. Then you have some logic to translate the multiplier into a position/angle -- which could also be it's own function.

In any case, great job!

2023-08-16 08:02 UTC, iansedano commented on 08-09-apis_requests/index.js
> +const sunPromise = getSun();
Using top level promises in this way can lead to unexpected behaviors and makes things hard to maintain.

Better to call the promises from within the functions that need them.

If you need the results from one promise in multiple places. Then you can have a wrapping function that calls the promise, packages the information in a data structure, and then distributes it where it needs to go.

For example:

```js
async function main(){
	const ipResponse = await getIpStack(); // only makes request and returns response
	const json = await ipResponse.json();
	const ipData = mapIpData(json) // optional: process json into simpler and more focussed format (not async)
	renderIpData(ipData); // updates the page with ip data (not async)

	const worldTimeResponse = await getWorldTime(ipData); // <--passing in ipData
	// ... etc
}
```

Note: this is just something off the top of my head. It may not be the best way to organize the code at a high level.

2023-08-16 08:02 UTC, iansedano commented on 08-09-apis_requests/index.js
> +    const {sunriseTime, sunsetTime, solarNoonTime} = await sunPromise;
Nice destructuring!

2023-08-23 13:24 UTC, LiveNathan commented on 08-09-apis_requests/index.js
> +    const {sunriseTime, sunsetTime, solarNoonTime} = await sunPromise;
destructuring? You think you can just go around making up words?

2023-08-23 13:37 UTC, LiveNathan reviewed
done

2023-08-23 13:38 UTC, merged